// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4bq_OwA8h_rhF9C6ueHaWZS84Ym62auw',
    appId: '1:209336982411:web:03a89c747ac38a8b222d8e',
    messagingSenderId: '209336982411',
    projectId: 'i2c-academy',
    authDomain: 'i2c-academy.firebaseapp.com',
    storageBucket: 'i2c-academy.firebasestorage.app',
    measurementId: 'G-QS77YXHX0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe8C68zsNwqw7IAMrkRkQnmUnOmFBuD9s',
    appId: '1:209336982411:android:d459d9fda8e0e6b7222d8e',
    messagingSenderId: '209336982411',
    projectId: 'i2c-academy',
    storageBucket: 'i2c-academy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9skfD5xtjK6RdVr7M-XczhmRpu1bqKfQ',
    appId: '1:209336982411:ios:387472e6ae4fb43a222d8e',
    messagingSenderId: '209336982411',
    projectId: 'i2c-academy',
    storageBucket: 'i2c-academy.firebasestorage.app',
    iosBundleId: 'com.example.skillgro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9skfD5xtjK6RdVr7M-XczhmRpu1bqKfQ',
    appId: '1:209336982411:ios:387472e6ae4fb43a222d8e',
    messagingSenderId: '209336982411',
    projectId: 'i2c-academy',
    storageBucket: 'i2c-academy.firebasestorage.app',
    iosBundleId: 'com.example.skillgro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4bq_OwA8h_rhF9C6ueHaWZS84Ym62auw',
    appId: '1:209336982411:web:3c25afaa75cb6b9c222d8e',
    messagingSenderId: '209336982411',
    projectId: 'i2c-academy',
    authDomain: 'i2c-academy.firebaseapp.com',
    storageBucket: 'i2c-academy.firebasestorage.app',
    measurementId: 'G-8X55H7RD9T',
  );
}
